POST http://0.0.0.0:9999/api/v1/child
Content-Type: application/json

{
    "name": "Otaviano Almeida",
    "rg": "184296924",
    "responsible" : {
        "cpf": "27325904010"
    },
    "shift": "matutino"
}

### 

POST http://0.0.0.0:9999/api/v1/child
Content-Type: application/json

{
    "name": "Felipe Fernandes",
    "rg": "350912713",
    "responsible" : {
        "cpf": "27325904010"
    },
    "shift": "matutino"
}

###

GET http://0.0.0.0:8888/api/v1/child/449381749
Content-Type: application/json

### 

GET http://0.0.0.0:9999/api/v1/65920117346/child
Content-Type: application/json

### 

DELETE http://0.0.0.0:8888/api/v1/child/449381749
Content-Type: application/json

{
    "name": "Otaviano Almeida",
    "rg": "449381749",
    "responsible" : {
        "cpf": "76315286080"
    },
    "shift": "matutino"
}

