### 

{
    "driver": {
        "cnh": "87891080365"
    },
    "school": {
        "cnpj": "98088292000160"
    },
    "child": {
        "rg": "449381749",
        "responsible": {
            "cpf": "76315286080"
        }
    },
    "status": "currently",
}