###
POST http://0.0.0.0:9999/api/v1/contract
Content-Type: application/json 

{
  "driver": {
    "id": 1,
    "name": "Amanda Fernandes Costa",
    "email": "afercosta19@gmail.com",
    "cnh": "55276739722",
    "address": {
      "street": "Rua Itamerendiba",
      "number": "30",
      "zip": "08120000"
    },
    "amount": 200,
    "phone": "+55 11 912345678",
    "car": {
        "model": "Fiat Uno",
        "year": "2010"
    },
    "pix": {"pix_key": "11912345678"}
  },
  "school": {
    "name": "E.M.E.F Professor Carlos Pasquale",
    "cnpj": "98088292000160",
    "address": {
      "street": "Rua Itamerendiba",
      "number": "30",
      "zip": "08120000"
    }
  },
  "child": {
    "name": "Felipe Fernandes",
    "rg": "350912713",
    "responsible": {
      "id": 1,
      "name": "Juliano Rodrigues Martins",
      "email": "julianoRodriguesMartins@teleworm.us",
      "cpf": "27325904010",
      "address": {
        "street": "Rua Masato Sakai",
        "number": "180",
        "zip": "08538300"
      },
      "customer_id": "cus_QpL9XTVfM6sBhD",
      "payment_method_id": "pm_1PxgSrLfFDLpePGLDi2tnFEm",
      "phone": "+55 11 930577222"
    }
  },
  "stripe": {
    "description_subscription": ""
  },
  "status": "currently"
}