version: '3.8'

services:
  venture:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: venture_container
    networks:
      - venture-network
    ports:
      - "9999:9999"
    restart: on-failure
    
networks:
  venture-network:
    driver: bridge

