// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Address is an autogenerated mock type for the Address type
type Address struct {
	mock.Mock
}

// Distance provides a mock function with given fields: origin, destination
func (_m *Address) Distance(origin string, destination string) (*float64, error) {
	ret := _m.Called(origin, destination)

	if len(ret) == 0 {
		panic("no return value specified for Distance")
	}

	var r0 *float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*float64, error)); ok {
		return rf(origin, destination)
	}
	if rf, ok := ret.Get(0).(func(string, string) *float64); ok {
		r0 = rf(origin, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*float64)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(origin, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddress creates a new instance of Address. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddress(t interface {
	mock.TestingT
	Cleanup(func())
}) *Address {
	mock := &Address{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
