// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/venture-technology/venture/internal/entity"

	uuid "github.com/google/uuid"
)

// ContractRepository is an autogenerated mock type for the ContractRepository type
type ContractRepository struct {
	mock.Mock
}

// Accept provides a mock function with given fields: contract
func (_m *ContractRepository) Accept(contract *entity.Contract) error {
	ret := _m.Called(contract)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Contract) error); ok {
		r0 = rf(contract)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cancel provides a mock function with given fields: _a0
func (_m *ContractRepository) Cancel(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Expired provides a mock function with given fields: _a0
func (_m *ContractRepository) Expired(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Expired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByDriver provides a mock function with given fields: cnh
func (_m *ContractRepository) GetByDriver(cnh string) ([]entity.EnableContract, error) {
	ret := _m.Called(cnh)

	if len(ret) == 0 {
		panic("no return value specified for GetByDriver")
	}

	var r0 []entity.EnableContract
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.EnableContract, error)); ok {
		return rf(cnh)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.EnableContract); ok {
		r0 = rf(cnh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EnableContract)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cnh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByResponsible provides a mock function with given fields: cpf
func (_m *ContractRepository) GetByResponsible(cpf string) ([]entity.EnableContract, error) {
	ret := _m.Called(cpf)

	if len(ret) == 0 {
		panic("no return value specified for GetByResponsible")
	}

	var r0 []entity.EnableContract
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.EnableContract, error)); ok {
		return rf(cpf)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.EnableContract); ok {
		r0 = rf(cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EnableContract)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySchool provides a mock function with given fields: cnpj
func (_m *ContractRepository) GetBySchool(cnpj string) ([]entity.EnableContract, error) {
	ret := _m.Called(cnpj)

	if len(ret) == 0 {
		panic("no return value specified for GetBySchool")
	}

	var r0 []entity.EnableContract
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.EnableContract, error)); ok {
		return rf(cnpj)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.EnableContract); ok {
		r0 = rf(cnpj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EnableContract)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cnpj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUUID provides a mock function with given fields: id
func (_m *ContractRepository) GetByUUID(id uuid.UUID) (*entity.EnableContract, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *entity.EnableContract
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entity.EnableContract, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.EnableContract); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EnableContract)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, attributes
func (_m *ContractRepository) Update(_a0 uuid.UUID, attributes map[string]interface{}) error {
	ret := _m.Called(_a0, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, map[string]interface{}) error); ok {
		r0 = rf(_a0, attributes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContractRepository creates a new instance of ContractRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContractRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContractRepository {
	mock := &ContractRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
