// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/venture-technology/venture/internal/entity"
)

// IEmailRepository is an autogenerated mock type for the IEmailRepository type
type IEmailRepository struct {
	mock.Mock
}

// Record provides a mock function with given fields: ctx, email
func (_m *IEmailRepository) Record(ctx context.Context, email *entity.Email) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Email) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIEmailRepository creates a new instance of IEmailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEmailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEmailRepository {
	mock := &IEmailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
