// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/venture-technology/venture/internal/entity"

	uuid "github.com/google/uuid"
)

// IContractRepository is an autogenerated mock type for the IContractRepository type
type IContractRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: _a0
func (_m *IContractRepository) Cancel(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: contract
func (_m *IContractRepository) Create(contract *entity.Contract) error {
	ret := _m.Called(contract)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Contract) error); ok {
		r0 = rf(contract)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Expired provides a mock function with given fields: _a0
func (_m *IContractRepository) Expired(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Expired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByCnh provides a mock function with given fields: cnh
func (_m *IContractRepository) FindAllByCnh(cnh *string) ([]entity.Contract, error) {
	ret := _m.Called(cnh)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCnh")
	}

	var r0 []entity.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) ([]entity.Contract, error)); ok {
		return rf(cnh)
	}
	if rf, ok := ret.Get(0).(func(*string) []entity.Contract); ok {
		r0 = rf(cnh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Contract)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(cnh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByCnpj provides a mock function with given fields: cnpj
func (_m *IContractRepository) FindAllByCnpj(cnpj *string) ([]entity.Contract, error) {
	ret := _m.Called(cnpj)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCnpj")
	}

	var r0 []entity.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) ([]entity.Contract, error)); ok {
		return rf(cnpj)
	}
	if rf, ok := ret.Get(0).(func(*string) []entity.Contract); ok {
		r0 = rf(cnpj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Contract)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(cnpj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByCpf provides a mock function with given fields: cpf
func (_m *IContractRepository) FindAllByCpf(cpf *string) ([]entity.Contract, error) {
	ret := _m.Called(cpf)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCpf")
	}

	var r0 []entity.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) ([]entity.Contract, error)); ok {
		return rf(cpf)
	}
	if rf, ok := ret.Get(0).(func(*string) []entity.Contract); ok {
		r0 = rf(cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Contract)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(cpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *IContractRepository) Get(_a0 uuid.UUID) (*entity.Contract, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entity.Contract, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.Contract); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Contract)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSimpleContractByTitle provides a mock function with given fields: title
func (_m *IContractRepository) GetSimpleContractByTitle(title *string) (*entity.Contract, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for GetSimpleContractByTitle")
	}

	var r0 *entity.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) (*entity.Contract, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(*string) *entity.Contract); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Contract)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, attributes
func (_m *IContractRepository) Update(_a0 uuid.UUID, attributes map[string]interface{}) error {
	ret := _m.Called(_a0, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, map[string]interface{}) error); ok {
		r0 = rf(_a0, attributes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIContractRepository creates a new instance of IContractRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIContractRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IContractRepository {
	mock := &IContractRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
