// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/venture-technology/venture/internal/entity"

	uuid "github.com/google/uuid"
)

// IInviteRepository is an autogenerated mock type for the IInviteRepository type
type IInviteRepository struct {
	mock.Mock
}

// Accept provides a mock function with given fields: _a0
func (_m *IInviteRepository) Accept(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: invite
func (_m *IInviteRepository) Create(invite *entity.Invite) error {
	ret := _m.Called(invite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Invite) error); ok {
		r0 = rf(invite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Decline provides a mock function with given fields: _a0
func (_m *IInviteRepository) Decline(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Decline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByCnh provides a mock function with given fields: cnh
func (_m *IInviteRepository) FindAllByCnh(cnh string) ([]entity.Invite, error) {
	ret := _m.Called(cnh)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCnh")
	}

	var r0 []entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Invite, error)); ok {
		return rf(cnh)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Invite); ok {
		r0 = rf(cnh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cnh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByCnpj provides a mock function with given fields: cnpj
func (_m *IInviteRepository) FindAllByCnpj(cnpj string) ([]entity.Invite, error) {
	ret := _m.Called(cnpj)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCnpj")
	}

	var r0 []entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Invite, error)); ok {
		return rf(cnpj)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Invite); ok {
		r0 = rf(cnpj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cnpj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *IInviteRepository) Get(_a0 uuid.UUID) (*entity.Invite, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entity.Invite, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.Invite); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIInviteRepository creates a new instance of IInviteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInviteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInviteRepository {
	mock := &IInviteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
