// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/venture-technology/venture/internal/entity"
)

// InviteRepository is an autogenerated mock type for the InviteRepository type
type InviteRepository struct {
	mock.Mock
}

// Accept provides a mock function with given fields: id
func (_m *InviteRepository) Accept(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: invite
func (_m *InviteRepository) Create(invite *entity.Invite) error {
	ret := _m.Called(invite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Invite) error); ok {
		r0 = rf(invite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Decline provides a mock function with given fields: id
func (_m *InviteRepository) Decline(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Decline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *InviteRepository) Get(id string) (*entity.Invite, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Invite, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Invite); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDriver provides a mock function with given fields: cnh
func (_m *InviteRepository) GetByDriver(cnh string) ([]entity.School, error) {
	ret := _m.Called(cnh)

	if len(ret) == 0 {
		panic("no return value specified for GetByDriver")
	}

	var r0 []entity.School
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.School, error)); ok {
		return rf(cnh)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.School); ok {
		r0 = rf(cnh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.School)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cnh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySchool provides a mock function with given fields: cnpj
func (_m *InviteRepository) GetBySchool(cnpj string) ([]entity.Driver, error) {
	ret := _m.Called(cnpj)

	if len(ret) == 0 {
		panic("no return value specified for GetBySchool")
	}

	var r0 []entity.Driver
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Driver, error)); ok {
		return rf(cnpj)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Driver); ok {
		r0 = rf(cnpj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Driver)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cnpj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInviteRepository creates a new instance of InviteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteRepository {
	mock := &InviteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
