// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/venture-technology/venture/internal/entity"
)

// ISchoolRepository is an autogenerated mock type for the ISchoolRepository type
type ISchoolRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, school
func (_m *ISchoolRepository) Create(ctx context.Context, school *entity.School) error {
	ret := _m.Called(ctx, school)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.School) error); ok {
		r0 = rf(ctx, school)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, cnpj
func (_m *ISchoolRepository) Delete(ctx context.Context, cnpj *string) error {
	ret := _m.Called(ctx, cnpj)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) error); ok {
		r0 = rf(ctx, cnpj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *ISchoolRepository) FindAll(ctx context.Context) ([]entity.School, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.School
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.School, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.School); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.School)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *ISchoolRepository) FindByEmail(ctx context.Context, email *string) (*entity.School, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.School
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (*entity.School, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) *entity.School); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.School)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, cnpj
func (_m *ISchoolRepository) Get(ctx context.Context, cnpj *string) (*entity.School, error) {
	ret := _m.Called(ctx, cnpj)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.School
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (*entity.School, error)); ok {
		return rf(ctx, cnpj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) *entity.School); ok {
		r0 = rf(ctx, cnpj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.School)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, cnpj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, school
func (_m *ISchoolRepository) Update(ctx context.Context, school *entity.School) error {
	ret := _m.Called(ctx, school)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.School) error); ok {
		r0 = rf(ctx, school)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISchoolRepository creates a new instance of ISchoolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISchoolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISchoolRepository {
	mock := &ISchoolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
