// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	value "github.com/venture-technology/venture/internal/value"
)

// WorkerCreateContract is an autogenerated mock type for the WorkerCreateContract type
type WorkerCreateContract struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: payload
func (_m *WorkerCreateContract) Enqueue(payload *value.CreateContractParams) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*value.CreateContractParams) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkerCreateContract creates a new instance of WorkerCreateContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerCreateContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerCreateContract {
	mock := &WorkerCreateContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
