BEGIN;

ALTER TABLE drivers ALTER COLUMN complement TYPE VARCHAR(100);
ALTER TABLE schools ALTER COLUMN complement TYPE VARCHAR(100);
ALTER TABLE responsibles ALTER COLUMN complement TYPE VARCHAR(100);

COMMIT;
