name: venture
development: true

server:
  host: "localhost"
  port: 9999
  secret: "venture"

database:
  dbuser: "postgres"
  dbport: 5432
  dbhost: "localhost"
  dbpassword: "password"
  dbname: "venture_staging"
  schema: "database/schema.sql"

cloud:
  region: "your-aws-region"
  accesskey: "your-access-key"
  secretkey: "your-secret-key"
  token: ""
  source: "your-aws-source-email"
  bucketname: "your-bucket-name"

cache:
  address: "localhost"
  password: "password"

uchiha:
  name: 'uchiha'
  queue: 'uchiha-topic'
  address-queue: '0.0.0.0:9092'

mongo:
  address: 'mongodb://0.0.0.0:27017'
  dbname: 'venturemdb'
  collection: 'uchiha-email'

google-cloud-secret:
  apikey: "your-apikey-google"
  endpoint-matrix-distance: "https://maps.googleapis.com/maps/api/distancematrix/json"

stripe-env:
  publickey: "your-stripe-public-key"
  secretkey: "your-stripe-secret-key"

admin:
  apikey: 'your-api-admin-key