POST http://0.0.0.0:8888/api/v1/invite
Content-Type: application/json

{
    "driver": {
        "cnh": "87891080365"
    },
    "school": {
        "cnpj": "98088292000160"
    }
}

###

GET http://0.0.0.0:8888/api/v1/driver/invite/87891080365
Content-Type: application/json

###

GET http://0.0.0.0:8888/api/v1/school/invite/98088292000160
Content-Type: application/json

###

GET http://0.0.0.0:8888/api/v1/invite/0191a408-409e-7f36-8fe6-61a68b3e5991
Content-Type: application/json

###

DELETE http://0.0.0.0:8888/api/v1/invite/0191a408-409e-7f36-8fe6-61a68b3e5991/decline
Content-Type: application/json

###
PATCH http://0.0.0.0:8888/api/v1/invite/0191a40c-55e7-7bbb-ac35-25ba5b1e7d9e/accept
Content-Type: application/json