POST http://0.0.0.0:9999/api/v1/responsible
Content-Type: application/json

{
    "name":"Juliano Rodrigues Martins",
    "email": "julianoRodriguesMartins@teleworm.us",
    "password": "123teste",
    "cpf": "27325904010",
    "status": "ok",
    "address": {
        "street": "Rua Masato Sakai",
        "number": "180",
        "zip": "08538300",
        "complement": "Manaca, bloco 1, apto 12"
    },
    "card": {
        
    },
    "phone": "+55 11 930577222"
}

###

GET http://0.0.0.0:9999/api/v1/responsible/65920117346
Content-Type: application/json

###

PATCH http://0.0.0.0:9999/api/v1/responsible/65920117346
Content-Type: application/json

{
    "name":"José Perlin",
    "email": "joseperil@gmail.com",
    "password": "123teste",
    "cpf": "76315286080",
    "status": "ok",
    "address": {
        "street": "Rua José Felicio",
        "number": "297",
        "zip": "08120320",
        "complement": "fundos"
    },
    "card": {
        "card_token": "tok_visa",
        "default": true
    },
    "phone": "+55 11 912345678"
}


### 

DELETE http://0.0.0.0:9999/api/v1/responsible/76315286080
Content-Type: application/json

###

POST http://0.0.0.0:9999/api/v1/responsible/card
Content-Type: application/json

{
    "cpf": "27325904010",
    "card": {
        "card_token": "tok_visa",
        "default": true
    }
}