POST http://0.0.0.0:8888/api/v1/responsible
Content-Type: application/json

{
    "name":"José Perlin",
    "email": "joseperil@gmail.com",
    "password": "123teste",
    "cpf": "76315286080",
    "status": "ok",
    "address": {
        "street": "Rua Itamerendiba",
        "number": "30",
        "zip": "08120520",
        "complement": "fundos"
    },
    "card": {
        "card_token": "tok_visa",
        "default": true
    },
    "phone": "+55 11 912345678"
}

###

GET http://0.0.0.0:8888/api/v1/responsible/76315286080
Content-Type: application/json

###

PATCH http://0.0.0.0:8888/api/v1/responsible/76315286080
Content-Type: application/json

{
    "name":"José Perlin",
    "email": "joseperil@gmail.com",
    "password": "123teste",
    "cpf": "76315286080",
    "status": "ok",
    "address": {
        "street": "Rua José Felicio",
        "number": "297",
        "zip": "08120320",
        "complement": "fundos"
    },
    "card": {
        "card_token": "tok_visa",
        "default": true
    },
    "phone": "+55 11 912345678"
}


### 

DELETE http://0.0.0.0:8888/api/v1/responsible/76315286080
Content-Type: application/json