PATCH http://0.0.0.0:8888/api/v1/responsible/76315286080
Content-Type: application/json

{
    "name":"José Perlin",
    "email": "joseperil@gmail.com",
    "password": "123teste",
    "cpf": "76315286080",
    "street": "Rua Itamerendiba",
    "number": "30",
    "zip": "08120520",
    "complement": "sobrado azul",
    "status": "ok",
    "card": {
        "card_token": "tok_visa",
        "default": false
    },
    "phone": "+55 11 940174467"
}