name: Run Go Tests on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: Create config.yaml
        run: |
          mkdir -p config
          cat <<EOF > config/config.yaml
          name: venture
          development: true

          server:
            host: ${{ secrets.SERVER_HOST }}
            port: ${{ secrets.SERVER_PORT }}
            secret: ${{ secrets.SERVER_SECRET }}

          database:
            dbuser: ${{ secrets.DB_USER }}
            dbport: ${{ secrets.DB_PORT }}
            dbhost: ${{ secrets.DB_HOST }}
            dbpassword: ${{ secrets.DB_PASSWORD }}
            dbname: ${{ secrets.DB_NAME }}

          cloud:
            region: ${{ secrets.AWS_REGION }}
            accesskey: ${{ secrets.AWS_ACCESS_KEY }}
            secretkey: ${{ secrets.AWS_SECRET_KEY }}
            token:
            source: ${{ secrets.AWS_SOURCE_EMAIL }}
            bucketname: ${{ secrets.AWS_BUCKET_NAME }}

          cache:
            address: ${{ secrets.REDIS_HOST }}
            password: ${{ secrets.REDIS_PASSWORD }}

          uchiha:
            name: uchiha
            queue: ${{ secrets.UCHIHA_TOPIC_NAME }}
            address-queue: ${{ secrets.UCHIHA_ADDRESS }}

          mongo:
            address: mongodb://0.0.0.0:27017
            dbname: venturemdb
            collection: uchiha-email

          google-cloud-secret:
            apikey: ${{ secrets.GOOGLE_API_KEY }}
            endpoint-matrix-distance: https://maps.googleapis.com/maps/api/distancematrix/json

          stripe-env:
            publickey: ${{ secrets.STRIPE_PUBLIC_KEY }}
            secretkey: ${{ secrets.STRIPE_SECRET_KEY }}

          admin:
            apikey: ${{ secrets.ADMIN_API_KEY }}

          dropbox:
            apikey: ${{ secrets.DROPBOX_API_KEY }}
            signature-request-endpoint: https://api.hellosign.com/v3/signature_request/send
          EOF

      - name: Print config.yaml for Debugging
        run: cat config/config.yaml

      - name: Run Go Tests
        run: go test ./...
