name: VentureLambdaSendEmailProdDeploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy_id:
        description: 'Deploy ID'
        required: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: Build Go binary for Lambda
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap cmd/lambda/send_email/main.go

      - name: Zip binary
        run: zip function.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-send-email-prod \
            --zip-file fileb://function.zip
